<a href="https://colab.research.google.com/github/tadashi000000/googlecolab001/blob/main/machinelearning001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

機械学習用

4-2-2 データの読込

In [4]:
from sklearn import datasets

#150個、3品種のアイリスの花のサイズからなるデータセット
#各花には4つの測定値と、品種を表す0から2のラベルがあります。データの総数は150です
iris = datasets.load_iris()

print(iris.data[:10]) #4つの測定値を10組表示
print(iris.data.shape) #測定値データの形状を表示
print(type(iris.data))
print(iris.target) #ラベルを全て表示


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
(150, 4)
<class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


4-2-3 データの前処理

In [3]:
from sklearn import preprocessing
from keras.utils import np_utils

# ---- 入力 データ ----
#今回は、入力データへの前処理として、入力の標準化を行います。
#標準化は、平均値が0、標準偏差が1になるように変換する処理です。

scaler = preprocessing.StandardScaler() #標準化のためのスケーラー
scaler.fit(iris.data) #変換のためのパラメータを計算
x = scaler.transform(iris.data) #データの変換
print(x[:10]) #入力を10件表示

# ---- 正解データ ----
t = np_utils.to_categorical(iris.target) #ラベルをone-hot表現に変換
print(t[:10]) #正解ラベルを10件表示

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]
 [-0.53717756  1.93979142 -1.16971425 -1.05217993]
 [-1.50652052  0.78880759 -1.34022653 -1.18381211]
 [-1.02184904  0.78880759 -1.2833891  -1.3154443 ]
 [-1.74885626 -0.36217625 -1.34022653 -1.3154443 ]
 [-1.14301691  0.09821729 -1.2833891  -1.44707648]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
